### ISSUE TITLE
Warning: Error in updateF7Radio: could not find function "updateF7Radio"

### ISSUE THREAD

**Issue by carlosyanez** [RinteRface/truelle#2]
Hi,

Thanks for developing this package.
Unfortunately, when I try to run run_app(), I get:

Loading required package: shiny

Listening on http://127.0.0.1:6993
Warning: Error in updateF7Radio: could not find function "updateF7Radio"
  4: shiny::runApp
  3: runGadget
  1: run_app

I can glimpse the UI on RStudio's viewer but then it disappear. When I log with my browser,. I can the following message: "Oups... disconnected"

I'm running R 4.1.0 on Macos . Happy to provide session info if that helps.

**Comment by DivadNojnarg** [comment]
Hi,

my guess it’s because you are running the shinyMobile CRAN version which is missing that function. The next CRAN version is going to be released soon. In the meantime try with the shinyMobile GitHub version.

**Comment by carlosyanez** [comment]
Thanks! I installed shinyMobile from Github and it's all working now.

**Comment by DivadNojnarg** [comment]
Released on CRAN
